#:schema node_modules/wrangler/config-schema.json
name = "faster-app"
main = "./main.py"
compatibility_date = "2024-09-24"
compatibility_flags = ["python_workers"]

[build]
command = "echo 'No build step required for Python Workers'"

# Environment variables that will be available in the Worker
[vars]
# These will be overridden by GitHub Actions for different environments
ENVIRONMENT = "development"
LOG_LEVEL = "info"

# Secrets (configured via wrangler secret put or GitHub secrets)
# DATABASE_URL - PostgreSQL connection string
# REDIS_URL - Redis connection string
# SUPABASE_URL - Supabase project URL
# SUPABASE_ANON_KEY - Supabase anonymous key
# SUPABASE_SERVICE_ROLE_KEY - Supabase service role key

# Resource limits
[limits]
cpu_ms = 10000

# Custom domains (configure after deployment)
# [[routes]]
# pattern = "api.yourdomain.com/*"
# zone_name = "yourdomain.com"

# Development environment
[env.development]
name = "faster-app-dev"

# Staging environment
[env.staging]
name = "faster-app-staging"

[env.staging.vars]
ENVIRONMENT = "staging"

# Production environment
[env.production]
name = "faster-app-prod"

[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "warn"