#:schema node_modules/wrangler/config-schema.json
name = "faster-app"
main = "./main.py"
compatibility_date = "2024-09-24"
compatibility_flags = ["python_workers"]

[build]
command = "echo 'No build step required for Python Workers'"

# Environment variables that will be available in the Worker
[vars]
# These will be overridden by GitHub Actions for different environments
ENVIRONMENT = "development"
LOG_LEVEL = "info"

# D1 Databases - Configured for each environment
# The database_id placeholders will be replaced during deployment
[[d1_databases]]
binding = "DB"
database_name = "faster-app-dev"
database_id = "DEV_DATABASE_ID_PLACEHOLDER"

# Secrets (configured via wrangler secret put or GitHub secrets)
# DATABASE_URL - Database connection string (PostgreSQL, SQLite, or D1)
# REDIS_URL - Redis connection string
# SUPABASE_URL - Supabase project URL
# SUPABASE_ANON_KEY - Supabase anonymous key
# SUPABASE_SERVICE_ROLE_KEY - Supabase service role key
# CLOUDFLARE_ACCOUNT_ID - For D1 HTTP mode (optional)
# CLOUDFLARE_API_TOKEN - For D1 HTTP mode (optional)
# D1_DATABASE_ID - For D1 HTTP mode (optional)

# Resource limits
[limits]
cpu_ms = 10000

# Custom domains (configure after deployment)
# [[routes]]
# pattern = "api.yourdomain.com/*"
# zone_name = "yourdomain.com"

# Development environment
[env.development]
name = "faster-app-dev"

[[env.development.d1_databases]]
binding = "DB"
database_name = "faster-app-dev"
database_id = "DEV_DATABASE_ID_PLACEHOLDER"

# Staging environment
[env.staging]
name = "faster-app-staging"

[env.staging.vars]
ENVIRONMENT = "staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "faster-app-staging"
database_id = "STAGING_DATABASE_ID_PLACEHOLDER"

# Production environment
[env.production]
name = "faster-app-prod"

[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "warn"

[[env.production.d1_databases]]
binding = "DB"
database_name = "faster-app-prod"
database_id = "PROD_DATABASE_ID_PLACEHOLDER"
