_format_version: "1.1"

###
### Consumers / Users
###
consumers:
  - username: "anon"
    keyauth_credentials:
      - key: "your-anon-key"
  - username: "service_role"
    keyauth_credentials:
      - key: "your-service-key"

###
### Access Control List
###
acls:
  - consumer: "anon"
    group: "anon"
  - consumer: "service_role"
    group: "admin"

###
### API Routes
###
services:
  - name: auth-v1
    url: http://supabase-auth:9999/verify
    routes:
      - name: auth-v1-all
        strip_path: true
        paths:
          - /auth/v1/
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - X-Real-IP
            - X-Client-Info
            - ApiKey
            - Authorization
          exposed_headers:
            - X-Auth-Token
            - X-Request-ID
          credentials: true
          max_age: 86400
      - name: key-auth
        config:
          hide_credentials: false
      - name: acl
        config:
          hide_groups_header: true
          allow:
            - anon
            - admin