"""add user event table

Revision ID: 5f36e6c0eb24
Revises: 7719df2d967d
Create Date: 2025-09-13 22:43:33.352531

"""

from collections.abc import Sequence
import logging

from alembic import op
import sqlalchemy as sa

logger = logging.getLogger(__name__)

# Revision identifiers, used by Alembic.
revision: str = "5f36e6c0eb24"
down_revision: str | None = '7719df2d967d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes.

    Example:
        op.create_table(
            "user",
            sa.Column("id", sa.Integer, primary_key=True),
            sa.Column("name", sa.String, nullable=False),
        )
    """
    # ### commands auto generated by Alembic - please adjust! ###
    _ = op.create_table('AUTH_USER_ACTION',
        sa.Column('N_IN_USED', sa.Integer(), server_default='1', nullable=False),
        sa.Column('D_CREATED_AT', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('D_UPDATED_AT', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('D_DELETED_AT', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('C_USER_AUTH_ID',sa.String(length=64), nullable=True),
        sa.Column('C_TRACE_ID',sa.String(length=128), nullable=True),
        sa.Column('C_SESSION_ID',sa.String(length=128), nullable=True),
        sa.Column('C_EVENT_TYPE',sa.String(length=32), nullable=False),
        sa.Column('C_EVENT_NAME',sa.String(length=64), nullable=False),
        sa.Column('C_EVENT_SOURCE',sa.String(length=32), nullable=False),
        sa.Column('D_TIMESTAMP', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('C_IP_ADDRESS',sa.String(length=45), nullable=True),
        sa.Column('C_USER_AGENT',sa.String(length=512), nullable=True),
        sa.Column('C_CLIENT_INFO',sa.String(length=256), nullable=True),
        sa.Column('C_REFERRER',sa.String(length=512), nullable=True),
        sa.Column('C_COUNTRY_CODE',sa.String(length=2), nullable=True),
        sa.Column('C_CITY',sa.String(length=128), nullable=True),
        sa.Column('C_TIMEZONE',sa.String(length=64), nullable=True),
        sa.Column('C_EVENT_PAYLOAD', sa.Text(), nullable=True),
        sa.Column('C_EXTRA_METADATA', sa.Text(), nullable=True),
        sa.Column('B_IS_PROCESSED', sa.Boolean(), server_default='0', nullable=False),
        sa.Column('C_PROCESSING_STATUS',sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_action_event_name', 'AUTH_USER_ACTION', ['C_EVENT_NAME'], unique=False)
    op.create_index('idx_user_action_event_type', 'AUTH_USER_ACTION', ['C_EVENT_TYPE'], unique=False)
    op.create_index('idx_user_action_session_id', 'AUTH_USER_ACTION', ['C_SESSION_ID'], unique=False)
    op.create_index('idx_user_action_source', 'AUTH_USER_ACTION', ['C_EVENT_SOURCE'], unique=False)
    op.create_index('idx_user_action_timestamp', 'AUTH_USER_ACTION', ['D_TIMESTAMP'], unique=False)
    op.create_index('idx_user_action_trace_id', 'AUTH_USER_ACTION', ['C_TRACE_ID'], unique=False)
    op.create_index('idx_user_action_type_time', 'AUTH_USER_ACTION', ['C_EVENT_TYPE', 'D_TIMESTAMP'], unique=False)
    op.create_index('idx_user_action_user_auth_id', 'AUTH_USER_ACTION', ['C_USER_AUTH_ID'], unique=False)
    op.create_index('idx_user_action_user_time', 'AUTH_USER_ACTION', ['C_USER_AUTH_ID', 'D_TIMESTAMP'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes.

    Example:
        op.drop_table("user")
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_action_user_time', table_name='AUTH_USER_ACTION')
    op.drop_index('idx_user_action_user_auth_id', table_name='AUTH_USER_ACTION')
    op.drop_index('idx_user_action_type_time', table_name='AUTH_USER_ACTION')
    op.drop_index('idx_user_action_trace_id', table_name='AUTH_USER_ACTION')
    op.drop_index('idx_user_action_timestamp', table_name='AUTH_USER_ACTION')
    op.drop_index('idx_user_action_source', table_name='AUTH_USER_ACTION')
    op.drop_index('idx_user_action_session_id', table_name='AUTH_USER_ACTION')
    op.drop_index('idx_user_action_event_type', table_name='AUTH_USER_ACTION')
    op.drop_index('idx_user_action_event_name', table_name='AUTH_USER_ACTION')
    op.drop_table('AUTH_USER_ACTION')
    # ### end Alembic commands ###
